#!/bin/bash
#
# up
# A Script to make alerts for pomodoro sessions.
# Copyright (C) 2023-2024 Ronald Jørnsøn
# 45grn6meov@runbox.email
# SPDX-License_Identifier: GPL-3.0-or-later
# https://www.gnu.org/licenses/gpl-3.0-standalone.html
# Version: 0.1.2.1

echo "How many pomodoro sessions do you want to do? (input 1-10)"
read sessions

[[ $sessions == ?(-)+([0-9]) ]] && echo "$1 is an integer"
#[[ $sessions =~ ^[0-9]+$ ]]
[ $sessions -le 10 ] || echo "You've made an invalid input. "

exit
#----------------------------
zenity --warning --text="Begin your work!" \
  && sleep 1500 \
  && notify-send "break" \
  && sleep 2 \
  && zenity --warning --text="First pomodoro session done. Take a short break" \
  && sleep 300 \
  && notify-send "Work" \
  && sleep 2 \
  && zenity --warning --text="Break is over. Time to work again!" \
  && sleep 1500 \
  && notify-send "Break" \
  && sleep 2 \
  && zenity --warning --text="Second pomodoro session done. Take a short break" \
  && sleep 300 \
  && notify-send "Work" \
  && sleep 2 \
  && zenity --warning --text="Break is over. Time to work again!" \
  && sleep 1500 \
  && notify-send "Break" \
  && sleep 2 \
  && zenity --warning --text="Third pomodoro session done. Take a longer break" \
  && sleep 900 \
  && notify-send "Work" \
  && sleep 2 \
  && zenity --warning --text="Begin your fourth pomodoro session!" \
  && sleep 1500 \
  && notify-send "Break" \
  && sleep 2 \
  && zenity --warning --text="Fourth pomodoro session done. Take a short break" \
  && sleep 300 \
  && notify-send "Work" \
  && sleep 2 \
  && zenity --warning --text="Break is over. Time to work again!" \
  && sleep 1500 \
  && notify-send "Break" \
  && sleep 2 \
  && zenity --warning --text="Fifth pomodoro session done. Take a short break" \
  && sleep 300 \
  && notify-send "Work" \
  && sleep 2 \
  && zenity --warning --text="Break is over. Time to do your last bit of work!" \
  && sleep 1500 \
  && notify-send "Break" \
  && sleep 2 \
  && zenity --warning --text="Well done. You are done for the day. Now go enjoy it!"
